# Generated by Django 4.2.3 on 2023-07-23 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('loan_type', models.CharField(choices=[('CAR', 'Car'), ('HOME', 'Home'), ('EDUCATIATIONAL', 'Educatiional'), ('PERSONAL', 'Personal')], max_length=100)),
                ('loan_amount', models.IntegerField()),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('term_period', models.IntegerField()),
                ('disbursement_date', models.DateField()),
                ('last_payment_date', models.DateField(null=True)),
                ('next_payment_date', models.DateField(null=True)),
                ('current_emi', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('current_due', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('principal_due_monthly', models.DecimalField(decimal_places=2, max_digits=12, null=True)),
                ('current_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12, null=True)),
                ('total_emi', models.IntegerField(default=0, null=True)),
            ],
            options={
                'db_table': 'loan_table',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('username', models.CharField(max_length=255)),
                ('aadhar_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('annual_income', models.IntegerField()),
                ('total_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('credit_score', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'user_model',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='LoanTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('date_due', models.DateField()),
                ('date_paid', models.DateField()),
                ('principal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='api.loanmodel')),
            ],
            options={
                'db_table': 'transaction_table',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='loanmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan', to='api.user'),
        ),
    ]
