# Generated by Django 4.2.3 on 2023-07-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
